### ISSUE TITLE
private.py

### ISSUE THREAD

**Issue by PonySchreck** [Xenorio/AfD-Blocklist-Checker#2]
Hey ich würde deine Bot token nicht so offen im code rein schmeißen :) 
An deiner stelle würde ich eine private.py in das projekt schmeißen, diese nicht zu git hinzufügen und die werte dann daraus laden
So hat nicht jeder direkt zugriff auf deinen Twitter bot :)  (damit man nichts "böses" mit ihm machen kann ;) )

zB: 
private.py:
```
consumer_key = "<consumer_key>"
consumer_secret = "<secret_key>"
```

checker.py
```
from private import consumer_key, consumer_secret

# rest of the code
```

**Comment by buggy82** [comment]
Hi Max. Dein Satz: "diese nicht zu git hinzufügen und die werte dann daraus laden" lässt mich ziemlich dumm aus der Wäsche gucken. Wie soll das denn gehen? Etwas laden, das nicht Teil des Projekts ist?

**Comment by Xenorio** [comment]
Wie @buggy82 schon sagte: man kann keine Dateien importieren, die nicht lokal gespeichert sind. 

Wenn du ne Methode zum z.B. Hashen des Keys kennst o.Ä., sodass man ihn nichtmehr auslesen kann bist du herzlich dazu eingeladen ne Pull Request zu machen. 

Und es ist ja nicht so dass der Authorisation Token im Code ist (Was nichtmal möglich wäre) also kann auch niemand auf Accounts zugreifen die ihm nicht gehören. Und falls trotzdem was "böses" gemacht wird und die Twitter Application gesperrt wird, kann ich ja immernoch ne neue Application einrichten und dann die Keys updaten.

**Comment by PonySchreck** [comment]
@buggy82 
nein damit meinte ich dass du die datei nicht in dein git projekt committest und die private.py lokal auf deinem computer/server/whatever lässt, damit niemand außer dir drauf zugreifen kannst :) auf die datei kannst du ja trotzdem zugreifen, nur ist sie eben nicht hochgeladen :)
war nur eine idee, weil ich es für unsicher halte die keys öffentlich irgendwo hochzuladen

@buggy82 Naja aber Hashfunktionen bringen dir ja auch nichts wenn du die Keys mit Salt usw. öffentlich hochlädst, das ist dann genauso sicher wie dein öffentlich hochgeladener Key

_____
Aber das mit dem AuthCode hab ich übersehen :) Wusste nicht dass man das manuell machen muss, danke für den hinweis :)

Naja, ist ja Geschmackssache ob man seine Keys öffentlich hochlädt oder nicht :)
Hab mal geforkt vlt findet ihr ja was tolles was ihr übernehmen wollt bei meinem pullrequest, wenn nicht dann ist das auch okay :D

**Comment by Xenorio** [comment]
Wenn man die Keys nicht öffentlich hochlädt, müsste sich jeder der das Skript benutzen will eine eigene Twitter Application einrichten. Und ich möchte die Benutzung auch für technisch eher unerfahrene Menschen so einfach wie möglich gestalten.

Ich seh das ganze hier jetzt mal als geklärt und schließe das Issue^^
